# kubernetes/task-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: task-manager
  labels:
    app: task-service
spec:
  type: ClusterIP
  
  selector:
    app: task-service
  
  ports:
  - name: http
    port: 6002
    targetPort: 6002
    protocol: TCP